### ISSUE TITLE
Propose the FedCM API as a work item for the FedIDCG

### ISSUE THREAD

**Issue by dj2** [fedidcg/proposals#1]
I'd like to propose the FedID CG takes up the [FedCM API](https://wicg.github.io/FedCM) as a work item. The FedCM API enables a website to request a users federated credentials from a user agent, and to have the user agent store the users federated credentials for future use.

The proposal is currently championed by:
 * Sam Goto
 * dan sinclair

**Comment by gffletch** [comment]
I was reading the updated FedCM API spec and while the introduction discusses the need to solve identity experiences that will be broken when support for 3rd party cookies is removed, many (if not most) of the use cases described are not broken by the removal of support for 3rd party cookies. Therefore, it is unclear to me if the proposed solution is a more general (as in new) way to support identity federation with the browser acting as a mediator in all identity flows, or a more specific proposal to address the flows that will be broken (e.g. single-sign-out, sign-in widget on relying party for federated sign-in). Is it possible to clarify this before acceptance as a work item for the group?

**Comment by dj2** [comment]
For the flows in the spec, I realized we never stated explicitly, but the cases being referenced are when the flow is done through an iframe. You can still do federated login using top level redirects, but after 3rd party cookie deprecation doing siginin within an iframe will not work as the IDP cookies will no longer be passed.

Would adding the the iframe clarification clear up the issue? Or are there other specific use-cases listed in the spec which are problematic from your point of view?

**Comment by samuelgoto** [comment]
> Therefore, it is unclear to me if the proposed solution is a more general (as in new) way to support identity federation with the browser acting as a mediator in all identity flows, or a more specific proposal to address the flows that will be broken (e.g. single-sign-out, sign-in widget on relying party for federated sign-in).

Good question, and sorry for not making it clear enough, but it is for the latter: the more specific / narrow proposal to address the flows that will be broken by the deprecation of third party cookies (used in iframes and XHR as @dj2 suggested).

**Comment by gffletch** [comment]
@dj2 @samuelgoto Thank you for your responses! I do think it would be good to clarify in the doc. Possibly in section 1.1 call out that these use cases refer to these flows occurring in an iframe. That would help to constrain the over all doc to be referring to flows that occur within iframes.

**Comment by dj2** [comment]
@gffletch I've integrated a change to hopefully clarify. I've got an outstanding request to add more context of third-party cookies in there. Does the clarification added address your concerns?

**Comment by timcappalli** [comment]
This was approved on the 2021-12-03 call: https://github.com/fedidcg/meetings/blob/main/2021/2021-12-03-notes.md

**Comment by gffletch** [comment]
@dj2 I'm glad to see the document was accepted by the WG. I do think the clarifications help. They might need to be restated and readers may gloss over them, but generally it sets a much narrower context which I think will help:)

My apologies for being so tardy in my response.

**Comment by travisleithead** [comment]
Note: this move has been completed. https://github.com/fedidcg/FedCM. Thanks everyone who helped!
